In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 nan]
 ['Spain' 38.0 61000.0]
 ['Germany' nan 82000.0]
 ['France' 35.0 58000.0]
 ['Spain' 29.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [6]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 66888.88888888889]
 ['Spain' 38.0 61000.0]
 ['Germany' 37.55555555555556 82000.0]
 ['France' 35.0 58000.0]
 ['Spain' 29.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 66888.88888888889]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 37.55555555555556 82000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 29.0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [12]:
print(x_train)

[[0.0 0.0 1.0 29.0 52000.0]
 [0.0 1.0 0.0 37.55555555555556 82000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [13]:
print(x_test)

[[0.0 1.0 0.0 30.0 66888.88888888889]
 [1.0 0.0 0.0 37.0 67000.0]]


In [14]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [15]:
print(y_test)

[0 1]


In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [18]:
print(x_train)

[[0.0 0.0 1.0 -1.2244850266024654 -1.1438606818751438]
 [0.0 1.0 0.0 -0.12973498830476032 1.1630852311503563]
 [1.0 0.0 0.0 0.6948819236597444 0.39410326014185626]
 [0.0 0.0 1.0 -0.0728648564451395 -0.45177690796749376]
 [0.0 0.0 1.0 -1.48040061997076 -1.4514534702785438]
 [1.0 0.0 0.0 1.2067131103963338 0.9323906398478062]
 [0.0 1.0 0.0 1.4626287037646284 1.2399834282512063]
 [1.0 0.0 0.0 -0.45673824649758143 -0.6824714992700438]]


In [19]:
print(x_test)

[[0.0 1.0 0.0 -1.0965272299183182 0.001068030515289694]
 [1.0 0.0 0.0 -0.20082265312928682 0.009612274637606236]]
